# Generated by Django 3.0.6 on 2020-05-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=64, null=True),
        ),
    ]
