# Generated by Django 3.0.6 on 2020-05-14 07:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200513_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='No Description', max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=64, null=True),
        ),
    ]
