# Generated by Django 3.0.6 on 2020-05-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20200514_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(default='No Description Added', max_length=100),
        ),
    ]
